//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pr7Entities2 : DbContext
    {
        public pr7Entities2()
            : base("name=pr7Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Компьютер> Компьютер { get; set; }
        public virtual DbSet<Программа> Программа { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Установка> Установка { get; set; }
    }
}
