//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Программа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Программа()
        {
            this.Установка = new HashSet<Установка>();
        }
    
        public int Код_программы { get; set; }
        public string Название { get; set; }
        public string Версия { get; set; }
        public string Класс { get; set; }
        public string Объем { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Установка> Установка { get; set; }
    }
}
